api:
  host: edge.ammp.io
  apiver: v0
data-endpoints:
  - name: default
    type: api
    config:
      host: edge.ammp.io
      apiver: v0
      timeout: 120
    isdefault: true
  - name: mqtt
    type: mqtt
    config:
      host: mqtt.ammp.io
      cert: ca.crt
      port: 8883