api:
  host: edge.ammp.io
  apiver: v0
data-endpoints:
  - name: api
    type: api
    config:
      host: edge.ammp.io
      apiver: v0
      timeout: 120
  - name: mqtt
    type: mqtt
    isdefault: true
    config:
      host: mqtt.ammp.io
      cert: ca.crt
      port: 8883
  # - name: mqtt-stage
  #   type: mqtt
  #   config:
  #     host: mqtt.stage.ammp.io
  #     cert: ca-stage.crt
  #     port: 8883
