name: stromm
version: '0.1.1'
summary: Secure Telemetry, Remote Operation and Monitoring for Mini-Grids
description: |
    Manages data collection and forwarding for AMMP.

grade: devel
confinement: strict

apps:
  stromm:
    command: bin/stromm
    plugs:
      - network

parts:
  stromm:
    plugin: python
    python-version: python3
    source: git@gitlab.com:ammp-services/stromm.git
    stage-packages:
        - libsnmp-dev
#        - snmp-mibs-downloader
        - python3-netifaces
# The following builds a blank "drivers" directory that's mapped to the drivers snap
  drivers:
    plugin: dump
    source: .
    build: |
      mkdir drivers
    stage:
      - drivers


plugs:
  drivers:
    interface: content
    content: drivers
    target: $SNAP/drivers
    default-provider: stromm-drivers:drivers