name: ammp-edge
version: 0.4
summary: Edge application for AMMP
description: |
    Manages data collection and forwarding for AMMP, and Asset Monioting and Management Platform.
    https://www.ammp.io/
    https://github.com/ammpio/ammp-edge

grade: stable
confinement: strict

apps:
  stromm:
    command: bin/ammp-edge -d
    daemon: simple
    restart-condition: always
#    restart-delay: 60
    plugs:
      - network
      - system-observe
      - hardware-observe
      - network-observe
      - serial-port

parts:
  ammp-edge:
    plugin: python
    python-version: python3
    source: https://github.com/ammpio/ammp-edge.git
    source-branch: master
    stage-packages:
        - libsnmp-dev
        - python3-netifaces
# Just to get the remote cfg YAML file
  ammp-edge-remote-cfg:
    plugin: dump
    source: https://github.com/ammpio/ammp-edge.git
    source-branch: master
    prime:
      - remote.yml
# Get the drivers directory also from git
  drivers:
    plugin: dump
    source: https://github.com/ammpio/ammp-edge.git
    source-branch: master
    prime:
      - drivers
