name: ammp-edge
version: git
summary: Edge application for AMMP
description: |
    Manages data collection and forwarding for AMMP, the Asset Monitoring and Management Platform.
    https://www.ammp.io/
    https://github.com/ammpio/ammp-edge

grade: stable
confinement: strict

base: core18

architectures:
  - build-on: amd64
  - build-on: armhf

apps:
  ammp-edge:
    command: bin/ammp_edge
    daemon: simple
    restart-condition: always
    after: [redis]
    plugs:
      - network
      - system-observe
      - hardware-observe
      - network-observe
      - serial-port
      - log-observe
    # The following is required in order to make libblas3 visible to nmap
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas"
  web-ui:
    command: flask run
    daemon: simple
    restart-condition: always
    plugs:
      - network-bind
    environment:
      FLASK_APP: web_ui
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8000
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas"
  nmap:
    command: nmap
    environment:
        LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas"
    plugs: [network, network-bind, network-control]
  redis:
    adapter: full
    command: bin/redis-server $SNAP/redis.conf --dir $SNAP_COMMON
    daemon: simple
    plugs: [network, network-bind]
  redis-cli:
    adapter: full
    command: bin/redis-cli
    plugs: [network]

parts:
  ammp-edge:
    plugin: python
    python-version: python3
    source: src
    stage-packages:
      - libsnmp-dev
      - nmap
    override-prime: |
      snapcraftctl prime
      "${SNAPCRAFT_PRIME}"/usr/bin/python3 \
        -m compileall \
        -q \
        --workers 0 \
        "${SNAPCRAFT_PRIME}"
  configs:
    plugin: dump
    source: config
    prime:
      - remote.yaml
      - redis.conf
  drivers:
    plugin: dump
    source: drivers
  jfq:
    plugin: nodejs
    nodejs-package-manager: npm
    source-type: git
    source: https://github.com/svet-b/jfq.git
    build-environment:
      - npm_config_unsafe_perm: 'true'
    stage:
      - -LICENSE
      - -README.md
  redis-server:
    plugin: make
    source: https://github.com/antirez/redis.git
    source-tag: 5.0.7
    source-depth: 1
    make-install-var: PREFIX
  bin:
    plugin: dump
    source: bin

plugs:
  provisioning-edge:
    interface: content
    content: ammp-edge-provisioning
    target: $SNAP/provisioning