name: stromm
version: '0.1.1'
summary: Secure Telemetry, Remote Operation and Monitoring for Mini-Grids
description: |
    Manages data collection and forwarding for AMMP.

grade: devel
confinement: strict

apps:
  stromm:
    command: bin/stromm
    plugs:
      - network

parts:
  stromm:
    plugin: python
    python-version: python3
    source: git@gitlab.com:ammp-services/stromm.git
    stage-packages:
        - libsnmp-dev
        - snmp-mibs-downloader
        - python3-netifaces
#  drivers:
#    plugin: dump
#    source: .
    stage:
      - src/drivers
    prime:
      - src/drivers
#    organize:
#      drivers: src/drivers


plugs:
  drivers:
    interface: content
    content: drivers
    target: $SNAP/drivers
    default-provider: stromm-drivers:drivers