name: ammp-edge
version: git
summary: Edge application for AMMP
description: |
    Manages data collection and forwarding for AMMP, the Asset Monitoring and Management Platform.
    https://www.ammp.io/
    https://github.com/ammpio/ammp-edge

grade: stable
confinement: strict

base: core18

architectures:
  - build-on: amd64
  - build-on: armhf

apps:
  ammp-edge:
    command: bin/ammp_edge
    daemon: simple
    restart-condition: always
#    restart-delay: 60
    plugs:
      - network
      - system-observe
      - hardware-observe
      - network-observe
      - serial-port
      - log-observe

parts:
  ammp-edge:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
        - libsnmp-dev
    override-prime: |
        snapcraftctl prime
        "${SNAPCRAFT_PRIME}"/usr/bin/python3 \
        -m compileall \
        -q \
        --workers 0 \
        "${SNAPCRAFT_PRIME}"
  ammp-edge-remote-cfg:
    plugin: dump
    source: .
    prime:
      - remote.yaml
  drivers:
    plugin: dump
    source: .
    prime:
      - drivers
  jfq:
    plugin: nodejs
    nodejs-package-manager: npm
    source-type: git
    source: https://github.com/svet-b/jfq.git
    build-environment:
      - npm_config_unsafe_perm: 'true'

plugs:
  provisioning-edge:
    interface: content
    content: ammp-edge-provisioning
    target: $SNAP/provisioning